<?xml version="1.0"?>
<package format="3">
  <name>dualarm_forcecon</name>
  <version>0.0.0</version>
  <description>Dual-arm force control package with external dualarm_kinematics backend.</description>

  <maintainer email="eunseop@example.com">eunseop</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>

  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>

  <depend>dualarm_forcecon_interfaces</depend>
  <depend>dualarm_kinematics</depend>

  <depend>eigen</depend>
  <depend>yaml-cpp</depend>
  <depend>pinocchio</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
